config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :areas, only: [:show] do
    resources :houses, only: [:index, :show] do
      get 'contact'
    end

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
  resources :searches, only:[:show, :index, :new, :create, :update]
  #resources :search, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :houses
  has_many :searches
  has_many :prices
  geocoded_by :area_postcode
  after_validation :geocode, if: :will_save_change_to_area_postcode?

  def commute_time
    CommuterTime.new({startcoord: [self.lat, self.lng]}).cityMapper_api
  end

  # def photo_safe

  # end
end

app/models/concerns/commuter_time.rb
require 'open-uri'

class CommuterTime
  # attr_accessor :startcoord, :,

  def initialize(options = {})
    @startcoord = options[:startcoord].join(",")
    @endcoord = userInput.join(",")
    # @cityMapper = time_return
  end

  def userInput
    # @startcoord = [current_user.lat, current_user.lng]
    [51.52495000,-0.07543900]

  end

  def potential_area
    @endcoord = area_id
  end

  def cityMapper_api
    cityMapper_url = "https://developer.citymapper.com/api/1/traveltime/?startcoord=#{@startcoord}&endcoord=#{@endcoord}&key=#{ENV["CITYMAPPER"]}"
    time_return = JSON.parse(open(cityMapper_url).read)
  end
end

app/models/house.rb
class House < ApplicationRecord
  include PgSearch::Model
  belongs_to :area
  geocoded_by :postcode
  after_validation :geocode, if: :will_save_change_to_postcode?

  validates :address, uniqueness: true

  pg_search_scope :search, against: [:bedroom, :bathroom, :price]

  def self.perform_search(keyword)
    if keyword.present?
      then House.search(keyword)
    else
      House.all
    end
  end
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :area
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
  geocoded_by :work_postcode
  after_validation :geocode, if: :will_save_change_to_work_postcode?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  has_many :searches
  has_many :areas, through: :searches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
end
def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_area, only: [:show, :edit, :update]

  def index
    @areas = Area.all
    # @area = Area.where(user_id: current_user.id).last.area
  end

  def show
    @homes = House.where(area_id: @area).shuffle.take(3)
    @schools = @area["schools"]["data"]["state"]["nearest"]
    @markers = @schools.map do |school|
      results = Geocoder.search(school["postcode"])
      next if results.empty?
      { lat: results.first.coordinates[0],
        lng: results.first.coordinates[1],
        infoWindow: render_to_string(partial: "school_map", locals: { school: school })
      }
    end
  end

  def edit
  end

  def geocode
    geocoded_by :address
    after_validation :geocode, if: :will_save_change_to_address?
  end

  def update
    if @area.update(area_params)
      redirect_to area_path(@area), notice: "#{@area.name} was successfully updated."
    else
      render :edit
    end
  end

  private

  def area_params
    params.require(:area).permit(:name, :sold_price, :schools, :crime, :demographics, :price, :growth, :demand, :image)
  end

  def set_area
    @area = Area.find(params[:id])
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show]

  def index
    @area = Area.find(params[:area_id])
    if params[:search].present?
      @houses = House.where(area:@area)
      @bedrooms = params[:search][:bedroom].to_i
      @houses = @houses.where(bedroom: @bedrooms) unless @bedrooms.zero?
      @bathrooms = params[:search][:bathroom].to_i
      @houses = @houses.where(bathroom: @bathrooms) unless @bathrooms.zero?
      @price = params[:search][:price].to_i
      @houses = @houses.where("price < #{@price}") unless @price.zero?
    else
      @houses = House.where(area:@area)
    end

    @houses = @houses.geocoded
    @markers = @houses.map do |house|
      {
        lat: house.latitude,
        lng: house.longitude,
        infoWindow: render_to_string(partial: "info_window_house", locals: { house: house })
      }
    end


  end

  def show
    @area = Area.find(params[:area_id])
    @house = House.find(params[:id])
    house_coordinates = {
      lat: @house.latitude,
      lng: @house.longitude,
      infoWindow: render_to_string(partial: "info_window_house", locals: { house: @house })
    }
    @markers = @house.restaurants["data"]["nearby"].map do |restaurant|
      {
        lat: restaurant["lat"].to_f,
        lng: restaurant["lng"].to_f,
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant })
      }
    end
    @markers << house_coordinates
  end

  def contact

  end

  private

  def house_params
    params.require(:house).permit(:address, :postcode, :bedroom, :bathroom, :square_feet, :council_tax, :ptal, :green_belt, :restaurants, :area_id)
  end

  def set_house
    @house = House.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def profile
    @income = current_user.income
    @credit = current_user.credit_score
    @dob = current_user.date_of_birth
    @deposit = current_user.deposit
    @borrowing = current_user.borrowing
    # @userInput= [current_user.lat, current_user.lng] - may need to be removed ?? thinking
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  # before_action :set_search, only: [:show]
  def index
  end

  def new
    @search = Search.new
  end

  def create
    @search = Search.new(search_params)
    @search.user_id = current_user.id
    session[:mortgage] = params["max-mortgage"]
    # @search.area_id = area_maths
    if @search.save
      redirect_to search_path(@search)
    else
      render :new
    end
  end

  def show
    @search = Search.find(params[:id])
    areas_match_distance = Area.near([@search.latitude, @search.longitude], @search.distance_to_work)
    # areas_match_price = areas_match_distance.where.AVERAGE_DEPOSIT
    max_borrow = @search.deposit.to_i + session[:mortgage].to_i
    @areas = areas_match_distance.select { |area| max_borrow >= area.sold_price["data"]["average"] }
    @areas = @areas.sort_by { |area| area.sold_price["data"]["average"] }.reverse


    if @areas.count > 3
      @areas = @areas.first(3)
    elsif @areas.count <= 3 && @areas.count != 0
      @areas = @areas.first(@areas.count)
    else
      @areas = []
    end
    # @areas = @area.map({area.name.CommuterTime}) this may need to be houses
  end

  def update
    @search = Search.find(search_params)
  end

  private

  def search_params
    params.require(:search).permit(:gross_annual, :deposit, :school, :distance_to_work, :work_postcode, :user_id, :crime, :price)
  end

  def area_maths
    area_name = distance_to_work
    preferred_area = Area.where(name: area_name)
    final_area = area_math_income(preferred_area)
    final_area.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/areas/_crime.html.erb
    <div class="area-show-container container-fluid">
      <div class="contailner-fluid area-title">
    <%= render "shared/jump" %>
    <h2 id="crime">Crime</h2>
    <p></p>
  </div>
     <div class="container-fluid area-back my-3">
       <div class="row">
         <div class="price-chart col-xs-12 col-md-6 col-lg-8">
            <%= bar_chart @area.crime["types"], title: "Breakdown of crime by type",  xtitle: "per 1000 population", ytitle: "Type of Crime" %>

            <p class="text-center"><%="Crime Type Definitions" %> <%= link_to "" , "https://www.met.police.uk/sd/stats-and-data/met/crime-type-definitions/", target: "_blank", class: "fas fa-info-circle", data: { toggle: "tooltip"}, title: "Crime Type Definitions"  %></p>
         </div>
       </div>
     </div>



    <div class="container-fluid area-back my-3 ">
      <div class="row">
        <div class="text-center price-chart col-xs-12 col-md-6 col-lg-6">
          <h5 class="my-3" style="font-weight:bolder;"><%= "Crime Overview for #{@area.name.capitalize}" %></h5>
          <p><%= "Crime Rating: #{@area.crime['crime_rating']}" %> </p>
          <p><%= "Number of crimes in last 12 months: #{@area.crime['crimes_last_12m']}" %></p>
          <p><%= "Number of crimes crimes per thousand: #{@area.crime['crimes_per_thousand']}" %></p>
        </div>
      </div>
   </div>

    <div class="container-fluid area-back my-3 ">
      <div class="row">
        <div class=" text-center price-chart col-xs-12 col-md-6 col-lg-8">
          <h5 class="my-3" style="font-weight:bolder;"><%= "Crime Observations for #{@area.name.capitalize}" %></h5>
          <p><%= @area.crime["observations"][0] %></p>
          <p><%= @area.crime["observations"][1] %></p>
          <p><%= @area.crime["observations"][2] %></p>
        </div>
      </div>
    </div>
  </div>

app/views/areas/_demand.html.erb
<div class="area-show-container container-fluid">
  <div class="container-fluid area-title">
    <%= render "shared/jump" %>
    <h2 id="demand">Demand</h2>
    <p></p>
  </div>

  <div class="container-fluid area-back my-3">
    <div class="row">
      <div class="price-chart col-xs-12 col-md-6 col-lg-8">
        <h5 class="text-center my-3" style="font-weight:bolder;"><%= "Purchase data for #{@area.name.capitalize}" %></h5>
          <div class="text-center">
            <p> <%= "Purchase Rating: #{@area.demand["demand_rating"]}" %></p>
            <p> <%= "Number of days on market: #{@area.demand["days_on_market"]}" %></p>
            <p> <%= "Total number of properties for sale: #{@area.demand["total_for_sale"]}" %></p>
            <p> <%= "Property turnover per month: #{@area.demand["turnover_per_month"]}" %></p>
            <p> <%= "Average number of sales per month: #{@area.demand["average_sales_per_month"].to_i}" %></p>
            <p> <%= "Months of inventory: #{@area.demand["months_of_inventory"]}" %></p>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/areas/_demographics.html.erb
<div class="area-show-container container-fluid">
  <div class="container-fluid area-title">
    <%= render "shared/jump" %>
    <h2 id="demographics">Demographics</h2>
    <p></p>
  </div>

  <div class="container-fluid area-back my-3">
    <div class="row">
      <div class="price-chart col-xs-12 col-md-6 col-lg-8">
        <p><%#="Breakdown of population by age for #{@area.name.capitalize}" %></p>
        <%= column_chart @area.demographics["data"]["age"], title: "Breakdown of population by age",xtitle: "Age range", ytitle: "% of pop" %>
      </div>
    </div>
  </div>

  <div class="container-fluid area-back">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-6">
        <div>
          <%= pie_chart @area.demographics["data"]["politics"]["results"], title: "Political vote last election"%>
        </div>
      </div>

      <div class="col-xs-12 col-md-6 col-lg-6">
        <%= pie_chart @area.demographics["data"]["social_grade"], title: "Social Grade breakdown"  %>
        <p class="text-center"><%="Social Grade Definitions" %> <%= link_to "" , "https://www.ukgeographics.co.uk/blog/social-grade-a-b-c1-c2-d-e", target: "_blank", class: "fas fa-info-circle", data: { toggle: "tooltip"}, title: "Social Grade Definitions"  %></p>
      </div>
    </div>
  </div>
     <div class="btn btn-main">
        <%= link_to'Back to Areas', search_path(current_user.searches.last), class: "button" %>
    </div>
    <div class="btn btn-main">
        <%= link_to'View All Properties', area_houses_path(@area), class: "button" %>
    </div>
</div>

app/views/areas/_form.html.erb
<div class="container">
  <%= simple_form_for(area) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <%= f.input :name %>
    </div>
    <div class="form-group">
    <%= f.input :price, as: :integer %>
    </div>
    <div class="form-inputs">
    <%= f.input :sold_price, as: :integer %>
    </div>
    <div class="form-inputs">
    <%= f.input :schools %>
    </div>
    <div class="form-inputs">
    <%= f.input :demographics %>
    </div>
    <div class="form-inputs">
    <%= f.input :growth %>
    </div>
    <div class="form-inputs">
    <%= f.input :demand %>
    </div>


    <div class="form-actions">
    <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/areas/_house.html.erb
<div class="area-sticky">
    <% @homes.each do |home| %>
      <div class="card-area-home-new house-card" style="margin: 32px;">
        <%= image_tag "houses/#{home.photo}", class: "img" %><br><br>
        <div class="house-card-info">
          <h7>£<%= number_with_delimiter(home.price)%></h7>
          <p><i class="fas fa-map-marked-alt">&nbsp;</i><%= home.address%></p>
          <p><i class="fas fa-bed">&nbsp;</i><%= home.bedroom%></p>
          <p><i class="fas fa-bath">&nbsp;</i><%= home.bathroom%></p>
          <div class="btn-hold">
            <h8><%= link_to 'See Property', area_house_path(home.area_id, home),class: "btn-ghost"%></h8>
          </div>
        </div>
      </div>
    <% end %>
</div>

 <%# @homes.each do |home| %>
  <!-- <div class="card-area-home"> -->
  <%#= image_tag "shoreditch/boxpark.jpg"%>
  <!-- <div class="card-area-home-footer"> -->
    <!-- <div> -->
      <%#= @homes.count %>
    <p><%#= home.address %></p>
    <p><%#= home.postcode %></p>
 <!--  </div>
</div>
</div> -->
<%# end %>

app/views/areas/_price.html.erb
<div class="area-show-container container-fluid">
  <div class="container-fluid area-title">
    <%= render "shared/jump" %>
    <h2 id="price">Price</h2>
    <p></p>
  </div>

  <div class="container-fluid area-back my-3">
    <div class="row">
      <div class="price-chart col-xs-12 col-md-6 col-lg-8">
        <p><%#ß="Average  price last 5 years in #{@area.name.capitalize}" %></p>
        <%= area_chart @area["growth"]["data"], title: "Average property price last 5 years",  xtitle: "Year", ytitle: "Price (£)" %>
      </div>
    </div>
  </div>


  <div class="container-fluid area-back my-3">
    <div class="row">
      <div class="price-chart col-xs-12 col-md-6 col-lg-8 my-3">
        <h5 class="text-center" style="font-weight:bolder;"><%= "Property % price change last 5 years in #{@area.name.capitalize}" %></h5>
        <table>
          <thead>
            <tr>
              <th>Year</th>
              <th>% Change</th>
            </tr>
          </thead>
          <tbody>
            <% @area.growth["data"]&.each do |growth| %>
              <% if growth[2].nil? %>
                <td><%= "#{growth[0]}:"%></td>
                <td><%= "No Data"%></td>
              <% else %>
                <tr>
                  <td><%= "#{growth[0]}:"%></td>
                  <td><%= "#{growth[2]}" %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/areas/_price_change.html.erb
 <p><%= "Property % price change last 5 years in #{@area.name.capitalize}" %></p>
<div class="my-3">
 <table>
  <thead>
    <tr>
      <th>Year</th>
      <th>% Change</th>
    </tr>
  </thead>
 <tbody>
    <% @area.growth["data"].each do |growth| %>
     <% if growth[2].nil? %>
     <td><%= "#{growth[0]}:"%></td>
     <td><%= "No Data"%></td>
       <% else %>
      <tr>
        <td><%= "#{growth[0]}:"%></td>
        <td><%= "#{growth[2]}" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>

app/views/areas/edit.html.erb
<%= render 'form', area: @area %>

app/views/houses/_form.html.erb
<!-- h1.page-header All the Houses

.house_search.form-group
  = form_tag(area_houses_path, method: "get") do
    = text_field_tag :search, nil, placeholder: "Search houses", class: "form-control"
    = submit_tag "", style: "display: none;"
 -->

app/views/houses/_info_window.html.erb
<h2><%= restaurant["name"] %></h2>
<p><%= restaurant["address"] %></p>

app/views/houses/_info_window_house.html.erb
<p><%= house.address %></p>

app/views/houses/index.html.erb
<div class="container-fluid house-description">
  <h1 id="title">List of Properties - <%=@area.name.upcase%></h1>
  <br>

  <!-- <input type=”text” name=”query” id=”query”> -->

  <div class = "house-form-search">
  <div class="row">
  <div class="col-12 col-md-8 form-left"><%= simple_form_for :search, url: area_houses_path(@area), method: :get do |f| %>
  <%= f.input :bedroom, collection: 1..6 %>
  <%= f.input :bathroom, collection: 1..3 %>
  <%= f.input :price, :label => "Price less than", collection: [300000, 400000, 500000, 600000, 700000, 800000, 900000, 1000000] %></div>
  <div class="col-6 col-md-4 form-right"><%= f.button :submit, 'Search', :class => "form-button" %>
    <% end %></div>
  </div>
</div>

  <% if @houses.empty?%>
  <h7>No results match your search</h7>
  <% end %>
  <br>

  <div class="cards house-description">
    <% @houses.each do |house| %>
      <div class="special-card">
        <%= image_tag "houses/#{house.photo}", class: "img" %><br>
        <div class="house-card-info">
          <h7 class = house-price>£<%= number_with_delimiter(house.price)%></h7>
          <p><i class="fas fa-map-marked-alt">&nbsp;</i><%= house.address%></p>
          <p><i class="fas fa-bed">&nbsp;</i> <%= house.bedroom%></p>
          <p><i class="fas fa-bath">&nbsp;</i> <%= house.bathroom%></p>
          <div class="btn-hold">
          <h8><%= link_to 'See Property', area_house_path(house.area_id, house),class: "btn-ghost"%></h8>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div
  id="map"
  style="width: 100%;
  height: 300px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
<div class="btn btn-main">
      <%= link_to'Back to Areas', search_path(current_user.searches.last), class: "button" %>
      </div>
</div>

app/views/pages/home.html.erb
  <div class="banner">
    <div class='card radius'>
      <h1>Welcome to <strong>Property AI</strong>!</h1>
      <br />
      <h5>The UK's smartest property portal</h5>
      <br />
      <div class="btn btn-main">
      <%= link_to'Let\'s get you started', new_search_path, class: "button" %>
      </div>
    </div>
  </div>


<div class="cards-base">
  <div class="card radius-left">
    <%= image_tag('house.gif') %>
    <br />
    <h6 class="card-title">We bring property search to<br />the next level</h6>
  </div>
  <div class="card radius-left">
    <%= image_tag('house4.gif') %>
    <br />
    <h6 class="card-title">Forget the usual filters</h6>
  </div>
  <div class="card radius-right">
    <%= image_tag('house3.gif') %>
    <br />
    <h6 class="card-title">We make your search easier</h6>
  </div>
</div>

<h2 class="cards_header">Most popular areas</h2>
<div class="cards-base">
  <div class="card radius-left">
    <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919205/areas/camden_sqpnfr.jpg") %>
    <br />
      <p><strong>Camden</strong></p>
      <div class="btn btn-main">
      <%= link_to'More info', new_search_path, class: "button" %>
      </div>
  </div>
<div class="card">
  <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919205/areas/hackney_wm9jn1.jpg") %>
  <br />
      <p><strong>Hackney</strong></p>
      <div class="btn btn-main">
      <%= link_to'More info', new_search_path, class: "button" %>
      </div>
  </div>
<div class="card radius-right">
  <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919196/areas/wandsworth_vri1rf.jpg") %>
  <br />
      <p><strong>Wandsworth</strong></p>
      <div class="btn btn-main">
      <%= link_to'More info', new_search_path, class: "button" %>
      </div>
  </div>
</div>

<h2 class="cards_header">Recently added houses</h2>
<div class="cards-base">
  <div class="card radius-left">
    <div class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919206/livingrooms/livingroom6_nawmrl.jpg") %>
        </div>
        <div class="carousel-item">
          <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919200/bedrooms/bedroom6_fwrjoa.jpg") %>
        </div>
        <div class="carousel-item">
          <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919199/kitchens/kitchen6_yhchl8.jpg") %>
        </div>
        <div class="carousel-item">
          <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919201/bathrooms/bathroom6_uhd2v4.jpg") %>
        </div>
      </div>
    </div>
    <br />
    <p>12 St. Peter's street<br /><strong>CAMDEN</strong><br />for £492,176</p>
    <div class="btn btn-main">
      <%= link_to'More info', new_search_path, class: "button" %>
      </div>
  </div>
  <div class="card">
    <div class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919204/livingrooms/livingroom3_js82us.jpg") %>
        </div>
        <div class="carousel-item">
          <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919202/bedrooms/bedroom3_fapibo.jpg") %>
        </div>
        <div class="carousel-item">
          <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919202/kitchens/kitchen3_vn6rjx.jpg") %>
        </div>
        <div class="carousel-item">
          <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919201/bathrooms/bathroom3_gjpjxp.jpg") %>
        </div>
      </div>
    </div>
     <br />
    <p>89 King Road<br /><strong>WANDSWORTH</strong><br />for £515,263</p>
    <div class="btn btn-main">
      <%= link_to'More info', new_search_path, class: "button" %>
      </div>
  </div>
  <div class="card radius-right">
    <div class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919203/livingrooms/livingroom2_unhq4t.jpg") %>
        </div>
        <div class="carousel-item">
          <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919200/bedrooms/bedroom2_wo3mfb.jpg") %>
        </div>
        <div class="carousel-item">
          <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919201/kitchens/kitchen2_sffzl8.jpg") %>
        </div>
        <div class="carousel-item">
          <%= cl_image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568919202/bathrooms/bathroom2_qura2z.jpg") %>
        </div>
      </div>
    </div>
     <br />
    <p>354 Huffelpuff Road<br /><strong>LAMBETH</strong><br />for £478,853</p>
    <div class="btn btn-main">
      <%= link_to'More info', new_search_path, class: "button" %>
      </div>
  </div>
</div>

app/views/searches/create.html.erb
<p>hello</p

<%= #form_tag area_path, #method: :get do %>
  <%= #text_field_tag :query,
    #params[:query],
     #class: "form-control",
    #placeholder: ""
  %>
  <%= #submit_tag "Search", class: "btn btn-primary" %>
<% #end %>


  <%= link_to'result of search', areas_path %>

app/views/searches/new.html.erb
<h2>Start Your Search Here</h2>


<%= render 'form', search: @search %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568920331/assets/logo_opp605.png") %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Search", new_search_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About us", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "FAQ", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag("https://res.cloudinary.com/dehjzta08/image/upload/v1568920331/assets/alias_px7ivv.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Account", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up/ Log in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>